<?php

declare(strict_types=1);

/**
 * Binding File Generator
 *
 * @author Omar Hamdan <omar@phpdot.com>
 * @license MIT
 */

namespace PHPdot\Package\Generator;

use PHPdot\Package\Scanner\PackageMeta;
use PHPdot\Package\Scanner\ScannedClass;

final class BindingFileGenerator
{
    /**
     * @param list<ScannedClass> $classes All scanned classes
     * @param array<string, PackageMeta> $packages Package metadata
     * @param string $containerPath Absolute path to container directory
     * @return list<string> Generated file paths
     */
    public function generate(
        array $classes,
        array $packages,
        string $containerPath,
    ): array {
        $byPackage = $this->groupByPackage($classes);
        $generated = [];

        foreach ($byPackage as $packageName => $group) {
            if (!$this->shouldGenerate($group)) {
                continue;
            }

            $configName = $this->resolveConfigName($group);

            if ($configName === null) {
                $configName = $this->deriveBindingName($packageName);
            }

            $bindingsDir = rtrim($containerPath, '/') . '/bindings';
            $filePath = $bindingsDir . '/' . $configName . '.php';

            if (is_file($filePath)) {
                continue;
            }

            if (!is_dir($bindingsDir)) {
                mkdir($bindingsDir, 0o755, true);
            }

            $meta = $packages[$packageName] ?? new PackageMeta(name: $packageName);
            $content = $this->generateFile($group, $meta, $packageName);
            file_put_contents($filePath, $content);
            $generated[] = $filePath;
        }

        return $generated;
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function shouldGenerate(array $group): bool
    {
        foreach ($group as $scanned) {
            if ($scanned->binds !== []) {
                return true;
            }

            foreach ($scanned->params as $param) {
                if (interface_exists($param) && !$this->isBoundByGroup($param, $group)) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function isBoundByGroup(string $interface, array $group): bool
    {
        foreach ($group as $scanned) {
            if (in_array($interface, $scanned->binds, true)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function resolveConfigName(array $group): ?string
    {
        foreach ($group as $scanned) {
            if ($scanned->configName !== null) {
                return $scanned->configName;
            }
        }

        return null;
    }

    private function deriveBindingName(string $packageName): string
    {
        $parts = explode('/', $packageName);

        return end($parts);
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function generateFile(array $group, PackageMeta $meta, string $packageName): string
    {
        $lines = [];
        $lines[] = "<?php\n";
        $lines[] = $this->generateHeader($group, $meta, $packageName);
        $lines[] = $this->generateUseStatements($group);
        $lines[] = "\nreturn static function (ContainerBuilder \$builder): void {\n";
        $lines[] = $this->generateOverrideSections($group);
        $lines[] = $this->generateContextualSections($group);
        $lines[] = "\n};\n";

        return implode('', $lines);
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function generateHeader(array $group, PackageMeta $meta, string $packageName): string
    {
        $lines = [];
        $lines[] = "\n/**";
        $lines[] = "\n * {$packageName} — Container Bindings";

        if ($meta->description !== '') {
            $lines[] = "\n * {$meta->description}";
        }

        $lines[] = "\n *";
        $lines[] = "\n * @package     {$packageName}";

        if ($meta->author !== '') {
            $lines[] = "\n * @author      {$meta->author}";
        }

        if ($meta->url !== '') {
            $lines[] = "\n * @see         {$meta->url}";
        }

        $lines[] = "\n * @generated   phpdot/package";
        $lines[] = "\n *";
        $lines[] = "\n * This file was auto-generated by phpdot/package.";
        $lines[] = "\n * Uncomment and modify any binding below.";
        $lines[] = "\n * This file will never be overwritten.";
        $lines[] = "\n *";
        $lines[] = "\n * Services registered by this package:";
        $lines[] = "\n *";

        foreach ($group as $scanned) {
            $lines[] = "\n *   " . $this->formatServiceLine($scanned, $group);
        }

        $configName = $this->resolveConfigName($group);
        $bindingName = $configName ?? $this->deriveBindingName($packageName);

        $lines[] = "\n *";
        $lines[] = "\n * Commands:";
        $lines[] = "\n *   php dot bindings:show {$bindingName}        Show original template";
        $lines[] = "\n *   php dot bindings:reset {$bindingName}       Reset to template";
        $lines[] = "\n */\n";

        return implode('', $lines);
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function formatServiceLine(ScannedClass $scanned, array $group): string
    {
        $short = $this->shortName($scanned->class);
        $scope = strtolower($scanned->scope->name);
        $padded = str_pad($short, 20);

        $detail = '';

        if ($scanned->configName !== null) {
            $detail = "Config DTO, hydrated from config/{$scanned->configName}.php";
        } elseif ($scanned->params !== []) {
            $paramNames = array_map($this->shortName(...), $scanned->params);
            $detail = '(' . implode(', ', $paramNames) . ')';
        } else {
            $detail = 'No dependencies';
        }

        foreach ($scanned->binds as $interface) {
            $detail .= ' → binds ' . $this->shortName($interface);
        }

        return "{$padded}{$scope}     {$detail}";
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function generateUseStatements(array $group): string
    {
        $imports = [
            'PHPdot\\Container\\ContainerBuilder',
        ];

        foreach ($group as $scanned) {
            $imports[] = $scanned->class;

            foreach ($scanned->binds as $interface) {
                $imports[] = $interface;
            }

            foreach ($scanned->params as $param) {
                if (interface_exists($param)) {
                    $imports[] = $param;
                }
            }
        }

        $imports = array_unique($imports);
        sort($imports);

        $lines = "\n";

        foreach ($imports as $import) {
            $lines .= "use {$import};\n";
        }

        return $lines;
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function generateOverrideSections(array $group): string
    {
        $sections = '';

        foreach ($group as $scanned) {
            foreach ($scanned->binds as $interface) {
                $shortInterface = $this->shortName($interface);
                $shortImpl = $this->shortName($scanned->class);

                $sections .= <<<PHP


                        /**
                         * Override {$shortInterface}
                         *
                         * Default: {$shortInterface} → {$shortImpl}
                         */

                        /*
                        \$builder->add({$shortInterface}::class, static function (\$c) {
                            return new YourImplementation(...);
                        })->singleton();
                        */

                    PHP;
            }
        }

        return $sections;
    }

    /**
     * @param list<ScannedClass> $group
     */
    private function generateContextualSections(array $group): string
    {
        $unboundInterfaces = [];

        foreach ($group as $scanned) {
            if ($scanned->configName !== null) {
                continue;
            }

            foreach ($scanned->params as $param) {
                if (interface_exists($param) && !$this->isBoundByGroup($param, $group)) {
                    $key = $param . '|' . $scanned->class;

                    if (!isset($unboundInterfaces[$key])) {
                        $unboundInterfaces[$key] = [
                            'interface' => $param,
                            'service' => $scanned->class,
                        ];
                    }
                }
            }
        }

        if ($unboundInterfaces === []) {
            return '';
        }

        $sections = "\n\n    /**\n     * Contextual Bindings\n     */\n";

        foreach ($unboundInterfaces as $binding) {
            $shortService = $this->shortName($binding['service']);
            $shortInterface = $this->shortName($binding['interface']);

            $sections .= <<<PHP

                    /*
                    \$builder->when({$shortService}::class)
                        ->needs({$shortInterface}::class)
                        ->provide(YourImplementation::class);
                    */

                PHP;
        }

        return $sections;
    }

    private function shortName(string $fqcn): string
    {
        $pos = strrpos($fqcn, '\\');

        return $pos !== false ? substr($fqcn, $pos + 1) : $fqcn;
    }

    /**
     * @param list<ScannedClass> $classes
     * @return array<string, list<ScannedClass>>
     */
    private function groupByPackage(array $classes): array
    {
        $grouped = [];

        foreach ($classes as $scanned) {
            $grouped[$scanned->package][] = $scanned;
        }

        return $grouped;
    }
}
