<?php

declare(strict_types=1);

/**
 * Config File Generator
 *
 * @author Omar Hamdan <omar@phpdot.com>
 * @license MIT
 */

namespace PHPdot\Package\Generator;

use PHPdot\Package\Scanner\PackageMeta;
use PHPdot\Package\Scanner\ScannedClass;
use ReflectionClass;

final class ConfigFileGenerator
{
    /**
     * @param list<ScannedClass> $classes All scanned classes
     * @param array<string, PackageMeta> $packages Package metadata
     * @param string $configPath Absolute path to config directory
     * @param list<string> $environments Environment names for override blocks
     * @return list<string> Generated file paths
     */
    public function generate(
        array $classes,
        array $packages,
        string $configPath,
        array $environments = ['development', 'production', 'staging'],
    ): array {
        $generated = [];

        foreach ($classes as $scanned) {
            if ($scanned->configName === null) {
                continue;
            }

            $filePath = rtrim($configPath, '/') . '/' . $scanned->configName . '.php';

            if (is_file($filePath)) {
                continue;
            }

            if (!is_dir($configPath)) {
                mkdir($configPath, 0o755, true);
            }

            $meta = $packages[$scanned->package] ?? new PackageMeta(name: $scanned->package);
            $content = $this->generateFile($scanned, $meta, $environments);
            file_put_contents($filePath, $content);
            $generated[] = $filePath;
        }

        return $generated;
    }

    /**
     * @param list<string> $environments
     */
    private function generateFile(ScannedClass $scanned, PackageMeta $meta, array $environments): string
    {
        $lines = [];
        $lines[] = "<?php\n";
        $lines[] = $this->generateHeader($scanned, $meta);
        $lines[] = "\nreturn [\n";

        $ref = new ReflectionClass($scanned->class);
        $constructor = $ref->getConstructor();

        $devOverrides = [];

        if ($constructor !== null) {
            foreach ($constructor->getParameters() as $param) {
                $name = $param->getName();

                $description = $scanned->paramDescriptions[$name]
                    ?? $this->humanize($name);

                $default = $param->isDefaultValueAvailable()
                    ? $this->formatDefault($param->getDefaultValue())
                    : "''";

                $lines[] = "\n    /**\n";
                $lines[] = "     * {$description}\n";
                $lines[] = "     */\n";
                $lines[] = "    '{$name}' => {$default},\n";

                $devOverride = $this->devOverride($name);

                if ($devOverride !== null) {
                    $devOverrides[$name] = $devOverride;
                }
            }
        }

        if ($environments !== []) {
            $lines[] = "\n    /**\n";
            $lines[] = "     * Environment overrides\n";
            $lines[] = "     *\n";
            $lines[] = "     * Values are merged on top of defaults based on the active environment.\n";
            $lines[] = "     * Handled automatically by phpdot/config.\n";
            $lines[] = "     */\n";

            foreach ($environments as $env) {
                if ($env === 'development' && $devOverrides !== []) {
                    $lines[] = "    '{$env}' => [\n";

                    foreach ($devOverrides as $key => $value) {
                        $lines[] = "        '{$key}' => {$value},\n";
                    }

                    $lines[] = "    ],\n";
                } else {
                    $lines[] = "    '{$env}' => [\n";
                    $lines[] = "    ],\n";
                }

                $lines[] = "\n";
            }
        }

        $lines[] = "];\n";

        return implode('', $lines);
    }

    private function generateHeader(ScannedClass $scanned, PackageMeta $meta): string
    {
        $lines = [];
        $lines[] = "\n/**";

        $lines[] = "\n * {$scanned->package}";

        if ($meta->description !== '') {
            $lines[] = "\n * {$meta->description}";
        }

        $lines[] = "\n *";
        $lines[] = "\n * @package     {$scanned->package}";

        if ($meta->author !== '') {
            $lines[] = "\n * @author      {$meta->author}";
        }

        if ($meta->url !== '') {
            $lines[] = "\n * @see         {$meta->url}";
        }

        $lines[] = "\n * @generated   phpdot/package";
        $lines[] = "\n *";
        $lines[] = "\n * This file was auto-generated by phpdot/package.";
        $lines[] = "\n * You own this file — edit freely. It will never be overwritten.";
        $lines[] = "\n *";
        $lines[] = "\n * Commands:";
        $lines[] = "\n *   php dot config:show {$scanned->configName}         Show original defaults";
        $lines[] = "\n *   php dot config:reset {$scanned->configName}        Reset to defaults";
        $lines[] = "\n */\n";

        return implode('', $lines);
    }

    private function devOverride(string $name): ?string
    {
        $lower = strtolower($name);

        if (str_contains($lower, 'ttl') || str_contains($lower, 'cache') || str_contains($lower, 'timeout')) {
            return '0';
        }

        if (str_contains($lower, 'debug')) {
            return 'true';
        }

        return null;
    }

    private function humanize(string $name): string
    {
        $words = str_replace('_', ' ', $name);

        return ucfirst($words);
    }

    private function formatDefault(mixed $value): string
    {
        if ($value === null) {
            return 'null';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if (is_string($value)) {
            return "'" . addslashes($value) . "'";
        }

        if (is_array($value)) {
            return $this->formatArray($value);
        }

        return "''";
    }

    /**
     * @param array<mixed> $value
     */
    private function formatArray(array $value): string
    {
        if ($value === []) {
            return '[]';
        }

        if (array_is_list($value)) {
            $items = array_map(fn(mixed $v): string => $this->formatDefault($v), $value);

            return '[' . implode(', ', $items) . ']';
        }

        $items = [];
        foreach ($value as $k => $v) {
            $items[] = "'" . addslashes((string) $k) . "' => " . $this->formatDefault($v);
        }

        return '[' . implode(', ', $items) . ']';
    }
}
