<?php

declare(strict_types=1);

/**
 * Definition Generator
 *
 * @author Omar Hamdan <omar@phpdot.com>
 * @license MIT
 */

namespace PHPdot\Package\Generator;

use PHPdot\Container\Scope;
use PHPdot\Package\Scanner\ScannedClass;

final class DefinitionGenerator
{
    /**
     * @param list<ScannedClass> $classes
     */
    public function generate(array $classes): string
    {
        $lines = [];
        $lines[] = "<?php\n";
        $lines[] = "// Auto-generated by phpdot/package. Do not edit.\n";
        $lines[] = "\ndeclare(strict_types=1);\n";
        $lines[] = "\nuse PHPdot\\Container\\Definition\\ScopedDefinition;";
        $lines[] = "\nuse PHPdot\\Container\\Scope;";
        $lines[] = "\nuse Psr\\Container\\ContainerInterface;\n";
        $lines[] = "\nreturn [\n";

        $grouped = $this->groupByPackage($classes);

        foreach ($grouped as $package => $group) {
            $lines[] = "\n    // ─── {$package} " . str_repeat('─', max(1, 55 - strlen($package))) . "\n";

            foreach ($group as $scanned) {
                $lines[] = $this->generateClass($scanned);

                foreach ($scanned->binds as $interface) {
                    $lines[] = $this->generateBinding($scanned, $interface);
                }
            }
        }

        $lines[] = "\n];\n";

        return implode('', $lines);
    }

    private function generateClass(ScannedClass $scanned): string
    {
        $fqcn = $this->fqcn($scanned->class);
        $scope = $this->scopeString($scanned->scope);

        if ($scanned->configName !== null) {
            return <<<PHP

                {$fqcn}::class => new ScopedDefinition(
                    scope: {$scope},
                    factory: static fn (ContainerInterface \$c): {$fqcn}
                        => \$c->get(\\PHPdot\\Config\\Configuration::class)->dto('{$scanned->configName}', {$fqcn}::class),
                ),

            PHP;
        }

        if ($scanned->params === []) {
            return <<<PHP

                {$fqcn}::class => new ScopedDefinition(
                    scope: {$scope},
                ),

            PHP;
        }

        $gets = [];
        foreach ($scanned->params as $param) {
            $gets[] = "            \$c->get({$this->fqcn($param)}::class),";
        }
        $getLines = implode("\n", $gets);

        return <<<PHP

            {$fqcn}::class => new ScopedDefinition(
                scope: {$scope},
                factory: static fn (ContainerInterface \$c): {$fqcn}
                    => new {$fqcn}(
            {$getLines}
                    ),
            ),

        PHP;
    }

    private function generateBinding(ScannedClass $scanned, string $interface): string
    {
        $ifqcn = $this->fqcn($interface);
        $cfqcn = $this->fqcn($scanned->class);
        $scope = $this->scopeString($scanned->scope);

        return <<<PHP

            {$ifqcn}::class => new ScopedDefinition(
                scope: {$scope},
                factory: static fn (ContainerInterface \$c): {$ifqcn}
                    => \$c->get({$cfqcn}::class),
            ),

        PHP;
    }

    private function scopeString(Scope $scope): string
    {
        return match ($scope) {
            Scope::SINGLETON => 'Scope::SINGLETON',
            Scope::SCOPED => 'Scope::SCOPED',
            Scope::TRANSIENT => 'Scope::TRANSIENT',
        };
    }

    private function fqcn(string $class): string
    {
        return '\\' . ltrim($class, '\\');
    }

    /**
     * @param list<ScannedClass> $classes
     * @return array<string, list<ScannedClass>>
     */
    private function groupByPackage(array $classes): array
    {
        $grouped = [];

        foreach ($classes as $scanned) {
            $grouped[$scanned->package][] = $scanned;
        }

        return $grouped;
    }
}
