<?php

declare(strict_types=1);

/**
 * Manifest Generator
 *
 * @author Omar Hamdan <omar@phpdot.com>
 * @license MIT
 */

namespace PHPdot\Package\Generator;

use PHPdot\Package\Scanner\ScannedClass;

final class ManifestGenerator
{
    /**
     * @param list<ScannedClass> $classes
     */
    public function generate(array $classes): string
    {
        $packages = [];

        foreach ($classes as $scanned) {
            $pkg = $scanned->package;

            if (!isset($packages[$pkg])) {
                $packages[$pkg] = [
                    'services' => [],
                    'configs' => [],
                    'bindings' => [],
                    'classes' => [],
                ];
            }

            $packages[$pkg]['services'][$scanned->class] = $scanned->scope->name;
            $packages[$pkg]['classes'][] = $scanned->class;

            if ($scanned->configName !== null) {
                $packages[$pkg]['configs'][$scanned->class] = $scanned->configName;
            }

            foreach ($scanned->binds as $interface) {
                $packages[$pkg]['bindings'][$interface] = $scanned->class;
            }
        }

        $exported = var_export($packages, true);
        $timestamp = date('c');

        return "<?php\n\n"
            . "// Auto-generated by phpdot/package. Do not edit.\n\n"
            . "return [\n"
            . "    'generated_at' => '{$timestamp}',\n"
            . "    'packages' => {$exported},\n"
            . "];\n";
    }
}
